export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const DAILY_ROUTE = '/'
export const MONTHLY_ROUTE = '/month'
export const FUTURE_ROUTE = '/future'
export const COLLECTION_ROUTE = '/collections'
export const NOT_FOUND = '*'